server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12

#spring:
  #security:
  #oauth2:
  #resourceserver:
    #jwt:
      #issuer-uri: ${OAUTH2_ISSUER_URI}
      #jwk-set-uri: ${OAUTH2_JWK_SET_URI}

spero:
  security:
    jwk-url: ${JWK_URL}
